### ISSUE TITLE
serverless-offline 6.x compatibility

### ISSUE THREAD

**Issue by joelvh** [logandk/serverless-rack#15]
@logandk I'm having issues upgrading to serverless-offline 6.x. Have you been able to use both of these plugins together?

The error I get indicates that the Ruby artifacts are not present in the root of the project when the offline function is triggered. When I copied the files there manually, I got past this error.

Any ideas?

Thanks!

```
[offline] Loading handler... (/code/rack_adapter)
Error: Command failed with exit code 1: ruby /code/node_modules/serverless-offline/dist/lambda/handler-runner/ruby-runner/invoke.rb rack_adapter handler
/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ./rack_adapter (LoadError)
	from /.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /code/node_modules/serverless-offline/dist/lambda/handler-runner/ruby-runner/invoke.rb:73:in `<main>'
    at makeError (/code/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/code/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at RubyRunner.run (/code/node_modules/serverless-offline/dist/lambda/handler-runner/ruby-runner/RubyRunner.js:104:16)
    at LambdaFunction.runHandler (/code/node_modules/serverless-offline/dist/lambda/LambdaFunction.js:318:20)
    at hapiHandler (/code/node_modules/serverless-offline/dist/events/http/HttpServer.js:457:18)
    at module.exports.internals.Manager.execute (/code/node_modules/@hapi/hapi/lib/toolkit.js:45:28)
    at Object.internals.handler (/code/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/code/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/code/node_modules/@hapi/hapi/lib/request.js:312:32)
    at Request._execute (/code/node_modules/@hapi/hapi/lib/request.js:221:9) {
  shortMessage: 'Command failed with exit code 1: ruby /code/node_modules/serverless-offline/dist/lambda/handler-runner/ruby-runner/invoke.rb rack_adapter handler',
  command: 'ruby /code/node_modules/serverless-offline/dist/lambda/handler-runner/ruby-runner/invoke.rb rack_adapter handler',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ./rack_adapter (LoadError)\n" +
    "\tfrom /.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\n" +
    "\tfrom /code/node_modules/serverless-offline/dist/lambda/handler-runner/ruby-runner/invoke.rb:73:in `<main>'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by joelvh** [comment]
I ended up just requiring the gem directly in my code and not using the plugin. Seems maybe the hooks changed in 6.x?
