### ISSUE TITLE
cannot load such file -- bundler/setup

### ISSUE THREAD

**Issue by leonardoalifraco** [logandk/serverless-rack#3]
Following the example on the readme I get this error:

```
Init error when loading handler rack_adapter.handler
{
"errorMessage": "cannot load such file -- bundler/setup",
"errorType": "Init<LoadError>",
"stackTrace": [
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/task/rack_adapter.rb:10:in `<top (required)>'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
]
}
START RequestId: 056272b6-2f57-41fe-b9b0-5a6a7bb16fb3 Version: $LATEST
Init error when loading handler rack_adapter.handler
{
"errorMessage": "cannot load such file -- bundler/setup",
"errorType": "Init<LoadError>",
"stackTrace": [
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/task/rack_adapter.rb:10:in `<top (required)>'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
]
}
END RequestId: 056272b6-2f57-41fe-b9b0-5a6a7bb16fb3
REPORT RequestId: 056272b6-2f57-41fe-b9b0-5a6a7bb16fb3	Duration: 218.89 ms	Billed Duration: 300 ms Memory Size: 1024 MB	Max Memory Used: 20 MB
Unknown application error occurred
Init<LoadError>
START RequestId: b23075d6-fc4f-4196-805a-ff227cc4fc5c Version: $LATEST
Init error when loading handler rack_adapter.handler
{
"errorMessage": "cannot load such file -- bundler/setup",
"errorType": "Init<LoadError>",
"stackTrace": [
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/task/rack_adapter.rb:10:in `<top (required)>'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
]
}
END RequestId: b23075d6-fc4f-4196-805a-ff227cc4fc5c
REPORT RequestId: b23075d6-fc4f-4196-805a-ff227cc4fc5c	Duration: 228.12 ms	Billed Duration: 300 ms Memory Size: 1024 MB	Max Memory Used: 20 MB
Unknown application error occurred
Init<LoadError>
Init error when loading handler rack_adapter.handler
{
"errorMessage": "cannot load such file -- bundler/setup",
"errorType": "Init<LoadError>",
"stackTrace": [
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/task/rack_adapter.rb:10:in `<top (required)>'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
]
}
START RequestId: 3e2ebcbf-d10e-4579-b2d5-ef7ef02789b2 Version: $LATEST
Init error when loading handler rack_adapter.handler
{
"errorMessage": "cannot load such file -- bundler/setup",
"errorType": "Init<LoadError>",
"stackTrace": [
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/task/rack_adapter.rb:10:in `<top (required)>'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
]
}
END RequestId: 3e2ebcbf-d10e-4579-b2d5-ef7ef02789b2
REPORT RequestId: 3e2ebcbf-d10e-4579-b2d5-ef7ef02789b2	Duration: 234.63 ms	Billed Duration: 300 ms Memory Size: 1024 MB	Max Memory Used: 20 MB
Unknown application error occurred
Init<LoadError>
```

**Comment by leonardoalifraco** [comment]
Update: Is working with bundler 1.17.3, but failing with bundler 2 onwards.

**Comment by logandk** [comment]
Thanks for the update - I didn't have a chance to look into this yet, but I will look into supporting bundler 1.x.
