### ISSUE TITLE
Utilizing without Serverless

### ISSUE THREAD

**Issue by mbround18** [logandk/serverless-rack#6]
When utilizing the gem without the serverless suite i get the following error on execution: 
```json
{
  "errorMessage": "undefined method `[]' for nil:NilClass",
  "errorType": "Function<NoMethodError>",
  "stackTrace": [
    "/var/task/vendor/bundle/ruby/2.5.0/gems/serverless-rack-1.0.3/lib/serverless_rack.rb:93:in `build_environ'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/serverless-rack-1.0.3/lib/serverless_rack.rb:223:in `handle_request'",
    "/var/task/function.rb:9:in `handler'"
  ]
}
```
This is my lambda.rb 
```
require 'serverless_rack'

$app ||= Proc.new do |env|
  ['200', {'Content-Type' => 'text/html'}, ['A barebones rack app.']]
end

def handler(event:, context:)
  puts 'Hello testing'
  handle_request(app: $app, event: event, context: context)
end
```

ive installed using 
```
bundle install --without development --path vendor/bundle
7z a lambda.zip *.rb src/ vendor/ *.ru .bundle Gemfile*
```
 i doing something wrong?

**Comment by mbround18** [comment]
![Annotation 2019-10-13 133457](https://user-images.githubusercontent.com/12646562/66722065-4c3ac580-edbe-11e9-8b3a-ea82d2683d14.png)
